name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-dev-on-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/deploy.sh
          chmod +x ./scripts/validate.sh

      - name: Validate CloudFormation template
        run: ./scripts/validate.sh

      - name: Deploy CloudFormation stack to dev environment
        run: ./scripts/deploy.sh dev

  deploy-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/deploy.sh
          chmod +x ./scripts/validate.sh

      - name: Validate CloudFormation template
        run: ./scripts/validate.sh

      - name: Deploy CloudFormation stack to selected environment
        run: ./scripts/deploy.sh ${{ github.event.inputs.environment }}

  destroy-manual:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'destroy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/destroy.sh

      - name: Destroy CloudFormation stack in selected environment
        run: ./scripts/destroy.sh ${{ inputs.environment }}
